urls.py
from django.urls import path

from . import views

app_name = 'bri'

urlpatterns = [
    path('', views.bri, name='bri'),
    path('completed/<str:class_group>/', views.completionView, name='compView')
]

models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from multiselectfield import MultiSelectField

########################
### Main site models ###
########################

class classEntry(models.Model):
    teacher = models.CharField(max_length=50)
    class_group = models.CharField(max_length=50)

    def __str__(self):
        return self.class_group

class userEntry(models.Model):
    user = models.CharField(max_length=10)
    class_group = models.ForeignKey(classEntry, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True, max_length=80)
    parent_email = models.EmailField(null=True, blank=True, max_length=80)
    
    def __str__(self):
        return self.user

    def save(self, *args, **kwargs):
        if self._state.adding:
            try:
                assignments = assignmentEntry.objects.all()
                super(userEntry, self).save(*args, **kwargs)
                for a in assignments:
                    if self.class_group == a.class_group:
                        completeEntry.objects.create(user=self, assignment=a)
            except:
                print('Problem connecting new user to assignments')
        else:
            super(userEntry, self).save(*args, **kwargs)


class assignmentEntry(models.Model):
    title = models.CharField(max_length=20)
    class_group = models.ForeignKey(classEntry, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    assigned_date = models.DateField(verbose_name='assigned date')
    due_date = models.DateField(verbose_name='due date')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self._state.adding:
            try:
                users = userEntry.objects.all()
                super(assignmentEntry, self).save(*args, **kwargs)
                for u in users:
                    if self.class_group == u.class_group:
                        completeEntry.objects.create(user=u, assignment=self)
            except:
                print('Problem connecting new assignment to users')
        else:
            super(assignmentEntry, self).save(*args, **kwargs)



class completeEntry(models.Model):
    user = models.ForeignKey(userEntry, on_delete=models.CASCADE)
    assignment = models.ForeignKey(assignmentEntry, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.user + '/' + self.assignment.title

views.py
from django.shortcuts import render

from .models import classEntry, userEntry, assignmentEntry, completeEntry

def assignmentSort(student):
    return student['assignment_id']

def bri(request):
    classes = classEntry.objects.all()
    return render(request, 'bri/bri.html', {'classes': classes})

def allClasses(request):
    return render(request, 'bri/classes.html')

def completionView(request, class_group='None'):
    #Gather relavent data from db
    users = userEntry.objects.filter(class_group=class_group).order_by('user')
    assignments = assignmentEntry.objects.filter(class_group=class_group).order_by('-id')
    completes = completeEntry.objects.filter(
            user__class_group=class_group).filter(
                    assignment__class_group=class_group).values(
            'id', 'user__user', 'assignment__title', 'completed')
    
    #If data is posted by client, check if data is valid, then update db
    if request.method == 'POST' and request.user.is_staff:
        ids = list(completes.values_list('id', flat=True))
        objs = []
        for k, v in request.POST.items():
            try:
                if int(k) in ids:
                    completes.filter(id=k).update(completed=v)
            except:
                pass

    #Build table from the above fields
    chart = [['']]
    counter = 0
    for a in assignments:
        chart[0].append(a.title)
    for u in users:
        counter += 1
        chart.append([])
        for i in completes.values():
            if i['user_id'] == u.id:
              chart[counter].append(i)
        chart[counter].sort(key=assignmentSort, reverse=True)
        chart[counter].insert(0, u.user)
    return render(request, 'bri/compChart.html', {'chart': chart})

templates/bri/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bri's Corner</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Fjalla+One|Lato:400i">
    <style>
    .w3-fjalla-one {
	    font-family: 'Fjalla One', sans-serif;
    }
    .w3-lato {
	    font-family: 'Lato', sans-serif;
    }
    </style>
</head>

<body class="w3-light-gray">

<div class="w3-container w3-white">
  <div class="w3-panel w3-dark-gray w3-card-2">
     <h1>Taking Time For The Good Stuff, And Automating The Rest</h1>
  </div>
</div>

<div class="w3-container">
  <div class="w3-container">
    {% block content %}{% endblock %}
  </div>
</div>
</body>
</html>

templates/bri/bri.html
{% extends 'bri/base.html'  %}

{% block content %}

<div class="w3-container">
  <h2>Completed Assignments</h2>
  <ul>
    {% for class in classes %}
      <li><a href="completed/{{ class.id }}">{{ class.class_group }}</a></li>
    {% endfor %}
  </ul>
</div>
<br>

{% endblock %}

templates/bri/compChart.html
{% extends 'bri/base.html' %}

{% block content %}

<div class="w3-container">
  <h1>Completed assignments</h1>
</div>
<div class="w3-container w3-responsive">
  {% if not request.user.is_authenticated %}
    <a href='/teacher' class='w3-right'>Teacher Login</a>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table class="w3-table-all w3-bordered">
      {% for row in chart %}
      <tr>
	{% if forloop.first %}
	  {% for item in row %}
	    <th>{{ item }}</th>
	  {% endfor %}
	{% else %}
	  {% for item in row %}
	    {% if forloop.first %}
	      <th style="white-space:nowrap;">{{ item }}</th>
	    {% else %}
	      <td style="white-space:nowrap;">
		{% if request.user.is_staff %}
		  <input type="radio" name={{ item.id }} value="Y" {{ item.completed|yesno:"checked," }}>Y</input>
		  <input type="radio" name={{ item.id }} value="N" {{ item.completed|yesno:",checked" }}>N</input>
		{% else %}
		  {% autoescape off %}
		  <span class="w3-text-{{ item.completed|yesno:"green,red" }}">{{ item.completed|yesno:"&#10004;,&#10008;" }}</span>
		  {% endautoescape %}
		{% endif %}
	      </td>
	    {% endif %}
	  {% endfor %}
	{% endif %}
      </tr>
      {% endfor %}
    </table>
    <br>
    {% if request.user.is_staff %}
      <input type="submit">
    {% endif %}
  </form>
</div>
<br>
<a href="{% url 'bri:bri' %}">Return to main page</a>

{% endblock %}